#!/bin/bash
source JsonBashUtil

USERNAME="IntTesting"

DELETE=$(curl -s -X DELETE "http://localhost:8080/users/${USERNAME}")
USER=$(curl -s -X POST "http://localhost:8080/users/${USERNAME}/?firstName=John&lastName=Doe&email=john.doe@gmail.com&password=JohnDoe123$")

INPUT=$(curl -s -X POST "http://localhost:8080/artworks/zeTitle?description=Best%20artwork%20ever&creationDate=2020-11-19&medium=blabla&imageUrl=zeImageURL&price=12&status=ForSale&dimensions=Big&collection=the%20best%20collection")
ARTWORK_ID=$( echo "$INPUT" | jsonValue artworkId )
ADD_USER=$(curl -s -X PUT "http://localhost:8080/artworks/${ARTWORK_ID}/add-artist/?username=${USERNAME}")
OUTPUT=$(curl -s -X GET 'http://localhost:8080/artworks' | grep -o "$USERNAME")

if [ -z "$OUTPUT" ]; then
  echo "ArtworkIntegrationTest Failed"
else
  echo "ArtworkIntegrationTest Passed"
fi

