#!/bin/bash
source JsonBashUtil

clearDB

# Run Tests
./EventIntegrationTest
./ShipmentIntegrationTest
./UserIntegrationTest
./ArtworkIntegrationTest
./OrderIntegrationTest
./PaymentIntegrationTest

clearDB