#!/bin/bash

function jsonValue() {
KEY=$1
num=$2
awk -F"[,:}]" '{for(i=1;i<=NF;i++){if($i~/'$KEY'\042/){print $(i+1)}}}' | tr -d '"' | sed -n ${num}p
}

function clearDB() {
    dbname="postgresql://ec2-3-210-178-167.compute-1.amazonaws.com:5432/d396rh6q72gvi6"
    username="wsykwbfslmpeqj"
PGPASSWORD=bc66db15c9717080e96f1adcdd8e909bea23d8858c37817e4a2230540c156371 psql $dbname $username << EOF
  \o /dev/null
  SET client_min_messages TO WARNING;
	TRUNCATE address CASCADE;
	TRUNCATE ag_order CASCADE;
	TRUNCATE gallery_event CASCADE;
	TRUNCATE artwork CASCADE;
	TRUNCATE payment CASCADE;
	TRUNCATE shipment CASCADE;
	TRUNCATE user_profile CASCADE;
EOF
}

function addTestElements() {
  clearDB
  USER1=$(curl -s -X POST "https://artgalleryapp-backend-0.herokuapp.com/users/johndoe/?firstName=John&lastName=Doe&email=john.doe@gmail.com&password=JohnDoe123$")
  USER2=$(curl -s -X POST "https://artgalleryapp-backend-0.herokuapp.com/users/janedoe/?firstName=Jane&lastName=Doe&email=jane.doe@gmail.com&password=JaneDoe123$")
  ARTWORK1=$(curl -s -X POST "https://artgalleryapp-backend-0.herokuapp.com/artworks/test1?description=Best%20artwork%20ever&creationDate=2020-11-19&medium=blabla&imageUrl=zeImageURL&price=12&status=ForSale&dimensions=Big&collection=the%20best%20collection")
  ARTWORK2=$(curl -s -X POST "https://artgalleryapp-backend-0.herokuapp.com/artworks/test2?description=Best%20artwork%20ever&creationDate=2020-11-19&medium=blabla&imageUrl=zeImageURL&price=12&status=ForSale&dimensions=Big&collection=the%20best%20collection")
}