#!/bin/bash
source JsonBashUtil

USERNAME="IntTesting"

DELETE=$(curl -s -X DELETE "https://artgalleryapp-backend-0.herokuapp.com/users/${USERNAME}")
USER=$(curl -s -X POST "https://artgalleryapp-backend-0.herokuapp.com/users/${USERNAME}/?firstName=John&lastName=Doe&email=john.doe@gmail.com&password=JohnDoe123$")

ARTWORK=$(curl -s -X POST "https://artgalleryapp-backend-0.herokuapp.com/artworks/zeTitle?description=Best%20artwork%20ever&creationDate=2020-11-19&medium=blabla&imageUrl=zeImageURL&price=12&status=ForSale&dimensions=Big&collection=the%20best%20collection")
ARTWORK_ID=$( echo "$ARTWORK" | jsonValue artworkId )

ORDER=$(curl -s -X POST "https://artgalleryapp-backend-0.herokuapp.com/orders/place-order/${USERNAME}/?artworkId=${ARTWORK_ID}")
ORDER_ID=$( echo "$ORDER" | jsonValue orderId )

PAYMENT=$(curl -s -X POST "https://artgalleryapp-backend-0.herokuapp.com/payments/?paymentForm=CreditCard&paymentDate=2000-01-01&cardNumber=009849003&expirationDate=2000-01-01&cvv=097&paymentId=111&paymentTime=12:15:00")
PAYMENT_ID=$( echo "$PAYMENT" | jsonValue paymentId )

INPUT=$(curl -s -X PUT "https://artgalleryapp-backend-0.herokuapp.com/orders/${ORDER_ID}/add-payment/?paymentId=${PAYMENT_ID}")
OUTPUT=$(curl -s -X GET 'https://artgalleryapp-backend-0.herokuapp.com/orders' | grep -o "$PAYMENT_ID")

if [ -z "$OUTPUT" ]; then
  echo "PaymentIntegrationTest Failed"
else
  echo "PaymentIntegrationTest Passed"
fi