#!/bin/bash
source JsonBashUtil

USERNAME="IntTesting"

DELETE=$(curl -s -X DELETE "http://localhost:8080/users/${USERNAME}")
USER=$(curl -s -X POST "http://localhost:8080/users/${USERNAME}/?firstName=John&lastName=Doe&email=john.doe@gmail.com&password=JohnDoe123$")

OUTPUT=$(curl -s -X GET 'http://localhost:8080/users' | grep -o "$USERNAME")

if [ -z "$OUTPUT" ]; then
  echo "UserIntegrationTest Failed"
else
  echo "UserIntegrationTest Passed"
fi
