#!/bin/bash
source JsonBashUtil

USERNAME="IntTesting"

DELETE=$(curl -s -X DELETE "https://artgalleryapp-backend-0.herokuapp.com/users/${USERNAME}")
USER=$(curl -s -X POST "https://artgalleryapp-backend-0.herokuapp.com/users/${USERNAME}/?firstName=John&lastName=Doe&email=john.doe@gmail.com&password=JohnDoe123$")

OUTPUT=$(curl -s -X GET 'https://artgalleryapp-backend-0.herokuapp.com/users' | grep -o "$USERNAME")

if [ -z "$OUTPUT" ]; then
  echo "UserIntegrationTest Failed"
else
  echo "UserIntegrationTest Passed"
fi
